pipeline_template: jar/Jenkinsfile-1
email_reply_to: mc-hypergage@salesforce.com
time_out_mins: 180                                    # (Optional) default shown
number_of_artifacts_to_keep: 3                        # (Optional) default shown
compliance_required: false                             # (Optional) default shown
docker_test_images:
   - dva/sfdc_centos7_java8_build
unit_tests_command: echo "no tests included"
# production_branch:                                    # (Optional) default shown
#     - master                                          # if using regex, append "r:" in front of pattern
production_branch:
    - evergage
# unit_tests_mount_point: /tmp/project                  # (Optional) default shown
# email_only_last_committer_on_dev_branch: false        # (Optional) default shown
# publish_jar_image: dva/sfdc_centos7_java_rpmbuild     # (Optional) default shown. This image will be used to run publish jar command
publish_jar_image: dva/sfdc_centos7_java_build_hypergage
